version: '3.9'

networks:
  chroma-net:
    driver: bridge

services:
  server:
    build:
      context: ./chroma-server
      dockerfile: Dockerfile
      target: chroma_server
    volumes:
      - ./chroma-server/:/chroma-server/
      - index_data:/index_data
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CLICKHOUSE_TCP_PORT=9000
    ports:
      - 8000:8000
    depends_on:
      - clickhouse
      - redis
    networks:
      - chroma-net

  worker:
    build:
      context: ./chroma-server
      dockerfile: DockerfileCelery
    command: celery worker --app=chroma_server.worker.celery --loglevel=info 
    volumes:
      - ./chroma-server/:/chroma-server/
      - index_data:/index_data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - server
      - redis
    networks:
      - chroma-net
  
  clickhouse:
    image: docker.io/bitnami/clickhouse:22.9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
    networks:
      - chroma-net

  redis:
    image: redis:6-alpine
    networks:
      - chroma-net

volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local

