version: '3.9'

networks:
  chroma-net:
    driver: bridge

services:
  server_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: chroma_server_test
    volumes:
      - ./:/chroma-server/
      - index_data:/index_data
    depends_on:
      - clickhouse_test
    networks:
      - chroma-net

  clickhouse_test:
    image: docker.io/bitnami/clickhouse:22.9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9008
      - CLICKHOUSE_HTTP_PORT=8124
    ports:
      - '8124:8124'
      - '9008:9008'
    networks:
      - chroma-net

volumes:
  index_data:
    driver: local

