apiVersion: batch/v1
kind: Job
metadata:
  name: logservice-migration
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: logservice-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - command:
            - "/bin/sh"
            - "-c"
            - "atlas migrate apply --url postgres://{{ .Values.logServiceMigration.username }}:{{ .Values.logServiceMigration.password }}@{{ .Values.logServiceMigration.netloc }}:{{ .Values.logServiceMigration.port }}/{{ .Values.logServiceMigration.dbName }}?sslmode={{ .Values.logServiceMigration.sslmode }}"
          image: "{{ .Values.logServiceMigration.image.repository }}:{{ .Values.logServiceMigration.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: migration
          env:
            {{ range .Values.logServiceMigration.env }}
            - name: {{ .name }}
              # TODO properly use flow control here to check which type of value we need.
{{ .value | nindent 14 }}
            {{ end }}

---
