name: Chroma Server Test

on:
  push:
    branches:
      - main
    paths:
      - 'chroma-server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'chroma-server/**'

jobs:
  test:
    strategy:
      matrix:
        python: ['3.10']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: |
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}:@github.com/".insteadOf "https://github.com/"
        cd chroma-server && python -m pip install -r requirements.txt -r requirements_dev.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install chroma_client
      run: cd chroma-client && pip install .
    - name: Test
      run: cd chroma-server && python -m pytest
